version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - nodejs
    networks:
      - app-network

  nodejs:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node app.js
    hostname: nodejs
    tty: true
    volumes:
      - "./node:/home/node/app"
      - "/home/node/app/node_modules"
    ports:
      - "9090:9090" 
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network
  
  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:

    